#!/bin/bash
# Automated Java 18 → 21 Upgrade Script
# Generated by AI DevOps Agent

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Java 18 → 21 Upgrade Script  ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo ""

# Check if running with correct Java version
check_java_version() {
    if command -v java &> /dev/null; then
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | awk -F '"' '{print $2}' | awk -F '.' '{print $1}')
        echo -e "Current Java version: ${YELLOW}$JAVA_VERSION${NC}"
        
        if [ "$JAVA_VERSION" != "21" ]; then
            echo -e "${YELLOW}⚠️  Warning: Java 21 not detected as default${NC}"
            echo "Please install Java 21 and set JAVA_HOME:"
            echo ""
            echo "  # macOS (Homebrew)"
            echo "  brew install openjdk@21"
            echo "  export JAVA_HOME=\$(/usr/libexec/java_home -v 21)"
            echo ""
            echo "  # Linux (Ubuntu/Debian)"
            echo "  sudo apt install openjdk-21-jdk"
            echo "  export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64"
            echo ""
            read -p "Continue anyway? (y/N): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                exit 1
            fi
        else
            echo -e "${GREEN}✅ Java 21 detected${NC}"
        fi
    else
        echo -e "${RED}❌ Java not found!${NC}"
        exit 1
    fi
}

# Create backup
create_backup() {
    BACKUP_DIR="../java-18-backup-$(date +%Y%m%d-%H%M%S)"
    echo -e "\n${YELLOW}📦 Creating backup...${NC}"
    cp -r . "$BACKUP_DIR"
    echo -e "${GREEN}✅ Backup created: $BACKUP_DIR${NC}"
    echo "$BACKUP_DIR" > .java-upgrade-backup
}

# Detect project type
detect_project_type() {
    if [ -f "pom.xml" ]; then
        echo -e "\n${GREEN}📋 Detected: Maven project${NC}"
        export PROJECT_TYPE="maven"
    elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        echo -e "\n${GREEN}📋 Detected: Gradle project${NC}"
        export PROJECT_TYPE="gradle"
    else
        echo -e "\n${YELLOW}⚠️  No Maven or Gradle project detected${NC}"
        export PROJECT_TYPE="unknown"
    fi
}

# Update Maven project
update_maven() {
    echo -e "\n${YELLOW}🔧 Updating Maven configuration...${NC}"
    
    # Backup pom.xml
    cp pom.xml pom.xml.backup
    
    # Update compiler source/target
    sed -i.bak 's/<maven\.compiler\.source>18</<maven.compiler.source>21</' pom.xml
    sed -i.bak 's/<maven\.compiler\.target>18</<maven.compiler.target>21</' pom.xml
    sed -i.bak 's/<java\.version>18</<java.version>21</' pom.xml
    
    # Update compiler plugin
    if ! grep -q "maven-compiler-plugin.*3\.1[1-9]" pom.xml; then
        echo -e "${YELLOW}⚠️  Consider updating maven-compiler-plugin to 3.12.1${NC}"
    fi
    
    rm -f pom.xml.bak
    echo -e "${GREEN}✅ Updated pom.xml${NC}"
    
    # Show changes
    echo -e "\n${YELLOW}Changes made:${NC}"
    diff -u pom.xml.backup pom.xml || true
}

# Update Gradle project
update_gradle() {
    echo -e "\n${YELLOW}🔧 Updating Gradle configuration...${NC}"
    
    GRADLE_FILE="build.gradle"
    if [ -f "build.gradle.kts" ]; then
        GRADLE_FILE="build.gradle.kts"
    fi
    
    # Backup
    cp "$GRADLE_FILE" "${GRADLE_FILE}.backup"
    
    # Update Java version
    sed -i.bak "s/sourceCompatibility.*=.*/sourceCompatibility = JavaVersion.VERSION_21/" "$GRADLE_FILE"
    sed -i.bak "s/targetCompatibility.*=.*/targetCompatibility = JavaVersion.VERSION_21/" "$GRADLE_FILE"
    sed -i.bak "s/languageVersion.*=.*JavaLanguageVersion\.of([0-9]*)/languageVersion = JavaLanguageVersion.of(21)/" "$GRADLE_FILE"
    
    rm -f "${GRADLE_FILE}.bak"
    echo -e "${GREEN}✅ Updated $GRADLE_FILE${NC}"
    
    # Show changes
    echo -e "\n${YELLOW}Changes made:${NC}"
    diff -u "${GRADLE_FILE}.backup" "$GRADLE_FILE" || true
}

# Update Dockerfile
update_dockerfile() {
    if [ -f "Dockerfile" ]; then
        echo -e "\n${YELLOW}🐳 Updating Dockerfile...${NC}"
        
        cp Dockerfile Dockerfile.backup
        
        # Update base images
        sed -i.bak "s/openjdk:18/eclipse-temurin:21/g" Dockerfile
        sed -i.bak "s/openjdk-18/openjdk-21/g" Dockerfile
        sed -i.bak "s/java-18/java-21/g" Dockerfile
        
        rm -f Dockerfile.bak
        echo -e "${GREEN}✅ Updated Dockerfile${NC}"
    fi
}

# Update GitHub Actions
update_github_actions() {
    if [ -d ".github/workflows" ]; then
        echo -e "\n${YELLOW}🔄 Updating GitHub Actions...${NC}"
        
        for workflow in .github/workflows/*.yml .github/workflows/*.yaml; do
            if [ -f "$workflow" ]; then
                cp "$workflow" "${workflow}.backup"
                sed -i.bak "s/java-version:.*'18'/java-version: '21'/" "$workflow"
                sed -i.bak "s/java-version:.*"18"/java-version: "21"/" "$workflow"
                rm -f "${workflow}.bak"
                echo -e "${GREEN}✅ Updated $workflow${NC}"
            fi
        done
    fi
}

# Test compilation
test_compilation() {
    echo -e "\n${YELLOW}🧪 Testing compilation...${NC}"
    
    if [ "$PROJECT_TYPE" = "maven" ]; then
        mvn clean compile
    elif [ "$PROJECT_TYPE" = "gradle" ]; then
        ./gradlew clean compileJava
    else
        echo -e "${YELLOW}⚠️  Manual compilation test required${NC}"
        return
    fi
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ Compilation successful!${NC}"
    else
        echo -e "${RED}❌ Compilation failed! Check errors above.${NC}"
        exit 1
    fi
}

# Main execution
main() {
    check_java_version
    create_backup
    detect_project_type
    
    case $PROJECT_TYPE in
        maven)
            update_maven
            ;;
        gradle)
            update_gradle
            ;;
        *)
            echo -e "${YELLOW}⚠️  Manual upgrade required${NC}"
            ;;
    esac
    
    update_dockerfile
    update_github_actions
    test_compilation
    
    echo -e "\n${GREEN}╔════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     Upgrade Completed Successfully     ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${GREEN}✅ Your project has been upgraded to Java 21${NC}"
    echo -e "\n${YELLOW}Next steps:${NC}"
    echo "  1. Review changes with: git diff"
    echo "  2. Run tests: mvn test (or ./gradlew test)"
    echo "  3. Commit changes: git add . && git commit -m 'Upgrade to Java 21'"
    echo "  4. Push to remote: git push"
    echo ""
    echo -e "${YELLOW}Rollback if needed:${NC}"
    echo "  BACKUP_DIR=\$(cat .java-upgrade-backup)"
    echo "  rm -rf ./*"
    echo "  cp -r \$BACKUP_DIR/* ."
}

# Run main function
main
