#!/usr/bin/env python3
"""
Centralized Configuration Management System
Generated by AI DevOps Agent

Purpose: implement centralized configuration management for solution tests
"""

import json
import os
from typing import Dict, Any, Optional
from pathlib import Path

class ConfigurationManager:
    """Centralized configuration manager for Solution Tests"""
    
    def __init__(self, config_dir: str = "configs"):
        self.config_dir = Path(config_dir)
        self.config_dir.mkdir(exist_ok=True)
        self.configs = {}
        self.load_all_configs()
    
    def load_all_configs(self):
        """Load all configuration files from the config directory"""
        config_files = self.config_dir.glob("*.json")
        for config_file in config_files:
            config_name = config_file.stem
            with open(config_file, 'r') as f:
                self.configs[config_name] = json.load(f)
        print(f"Loaded {len(self.configs)} configuration(s)")
    
    def get_config(self, config_name: str) -> Optional[Dict[str, Any]]:
        """Retrieve configuration by name"""
        return self.configs.get(config_name)
    
    def save_config(self, config_name: str, config_data: Dict[str, Any]):
        """Save configuration to file"""
        config_path = self.config_dir / f"{config_name}.json"
        with open(config_path, 'w') as f:
            json.dump(config_data, f, indent=2)
        self.configs[config_name] = config_data
        print(f"Saved configuration: {config_name}")
    
    def get_taxpayer_config(self, taxpayer_id: str) -> Optional[Dict[str, Any]]:
        """Get taxpayer-specific configuration"""
        taxpayer_configs = self.get_config("taxpayers")
        if taxpayer_configs:
            return taxpayer_configs.get(taxpayer_id)
        return None
    
    def get_environment_config(self, env_name: str) -> Optional[Dict[str, Any]]:
        """Get environment-specific configuration"""
        env_configs = self.get_config("environments")
        if env_configs:
            return env_configs.get(env_name)
        return None
    
    def get_product_config(self, product_name: str) -> Optional[Dict[str, Any]]:
        """Get product-specific configuration"""
        product_configs = self.get_config("products")
        if product_configs:
            return product_configs.get(product_name)
        return None

if __name__ == "__main__":
    # Example usage
    config_manager = ConfigurationManager()
    
    # Create sample configurations
    sample_environments = {
        "dev": {"url": "https://dev.example.com", "timeout": 30},
        "staging": {"url": "https://staging.example.com", "timeout": 30},
        "prod": {"url": "https://prod.example.com", "timeout": 60}
    }
    config_manager.save_config("environments", sample_environments)
    
    sample_taxpayers = {
        "taxpayer1": {"id": "001", "name": "Test Corp", "jurisdiction": "US"},
        "taxpayer2": {"id": "002", "name": "Demo Inc", "jurisdiction": "CA"}
    }
    config_manager.save_config("taxpayers", sample_taxpayers)
    
    print("\nCentralized Configuration Management System initialized!")
    print(f"Configuration directory: {config_manager.config_dir.absolute()}")
