#!/bin/bash
# Java 11 to Java 21 Upgrade Script
# Generated by AI DevOps Agent
# Automates the upgrade process from Java 11 to Java 21

set -e

echo "======================================================================="
echo "Java 11 → Java 21 Upgrade Script"
echo "======================================================================="
echo ""

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo "ℹ️  $1"
}

# Detect project type
detect_project_type() {
    if [ -f "pom.xml" ]; then
        echo "maven"
    elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        echo "gradle"
    else
        echo "unknown"
    fi
}

PROJECT_TYPE=$(detect_project_type)
print_info "Detected project type: $PROJECT_TYPE"

# Backup current configuration
backup_config() {
    print_info "Creating backup of current configuration..."
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="./backup_java11_$TIMESTAMP"
    mkdir -p "$BACKUP_DIR"
    
    if [ "$PROJECT_TYPE" == "maven" ]; then
        cp pom.xml "$BACKUP_DIR/" 2>/dev/null || true
    elif [ "$PROJECT_TYPE" == "gradle" ]; then
        cp build.gradle* "$BACKUP_DIR/" 2>/dev/null || true
        cp settings.gradle* "$BACKUP_DIR/" 2>/dev/null || true
    fi
    
    [ -f "Dockerfile" ] && cp Dockerfile "$BACKUP_DIR/" 2>/dev/null || true
    
    print_success "Backup created at $BACKUP_DIR"
}

# Update Maven pom.xml
update_maven() {
    print_info "Updating Maven pom.xml..."
    
    if [ -f "pom.xml" ]; then
        # Backup original
        cp pom.xml pom.xml.bak
        
        # Update Java version properties
        sed -i.tmp 's/<maven\.compiler\.source>11</<maven.compiler.source>21</g' pom.xml
        sed -i.tmp 's/<maven\.compiler\.target>11</<maven.compiler.target>21</g' pom.xml
        sed -i.tmp 's/<java\.version>11</<java.version>21</g' pom.xml
        
        rm -f pom.xml.tmp
        
        print_success "Maven configuration updated"
    else
        print_warning "pom.xml not found, skipping Maven update"
    fi
}

# Update Gradle build files
update_gradle() {
    print_info "Updating Gradle configuration..."
    
    if [ -f "build.gradle" ]; then
        cp build.gradle build.gradle.bak
        
        sed -i.tmp 's/JavaVersion\.VERSION_11/JavaVersion.VERSION_21/g' build.gradle
        sed -i.tmp 's/sourceCompatibility = 11/sourceCompatibility = 21/g' build.gradle
        sed -i.tmp 's/targetCompatibility = 11/targetCompatibility = 21/g' build.gradle
        sed -i.tmp "s/sourceCompatibility = '11'/sourceCompatibility = '21'/g" build.gradle
        sed -i.tmp "s/targetCompatibility = '11'/targetCompatibility = '21'/g" build.gradle
        
        rm -f build.gradle.tmp
        print_success "Gradle build.gradle updated"
    fi
    
    if [ -f "build.gradle.kts" ]; then
        cp build.gradle.kts build.gradle.kts.bak
        
        sed -i.tmp 's/JavaVersion\.VERSION_11/JavaVersion.VERSION_21/g' build.gradle.kts
        
        rm -f build.gradle.kts.tmp
        print_success "Gradle build.gradle.kts updated"
    fi
    
    if [ ! -f "build.gradle" ] && [ ! -f "build.gradle.kts" ]; then
        print_warning "Gradle build files not found, skipping Gradle update"
    fi
}

# Update Dockerfile
update_dockerfile() {
    if [ -f "Dockerfile" ]; then
        print_info "Updating Dockerfile..."
        cp Dockerfile Dockerfile.bak
        
        sed -i.tmp 's/openjdk:11/eclipse-temurin:21/g' Dockerfile
        sed -i.tmp 's/openjdk:11-jre/eclipse-temurin:21-jre/g' Dockerfile
        sed -i.tmp 's/openjdk:11-jdk/eclipse-temurin:21-jdk/g' Dockerfile
        
        rm -f Dockerfile.tmp
        print_success "Dockerfile updated"
    fi
}

# Update GitHub Actions workflow
update_github_actions() {
    if [ -d ".github/workflows" ]; then
        print_info "Updating GitHub Actions workflows..."
        
        for workflow in .github/workflows/*.yml .github/workflows/*.yaml; do
            if [ -f "$workflow" ]; then
                cp "$workflow" "$workflow.bak"
                sed -i.tmp "s/java-version: '11'/java-version: '21'/g" "$workflow"
                sed -i.tmp 's/java-version: 11/java-version: 21/g' "$workflow"
                rm -f "$workflow.tmp"
            fi
        done
        
        print_success "GitHub Actions workflows updated"
    fi
}

# Verify Java 21 installation
verify_java_installation() {
    print_info "Verifying Java 21 installation..."
    
    if command -v java &> /dev/null; then
        JAVA_VERSION=$(java -version 2>&1 | head -n 1)
        echo "   Current: $JAVA_VERSION"
        
        if echo "$JAVA_VERSION" | grep -q "21"; then
            print_success "Java 21 is installed"
            return 0
        else
            print_warning "Java 21 not detected, please install it manually"
            return 1
        fi
    else
        print_error "Java not found in PATH"
        return 1
    fi
}

# Run the upgrade
main() {
    echo ""
    print_info "Starting Java 11 to Java 21 upgrade process..."
    echo ""
    
    # Create backup
    backup_config
    echo ""
    
    # Update configurations based on project type
    case $PROJECT_TYPE in
        maven)
            update_maven
            ;;
        gradle)
            update_gradle
            ;;
        *)
            print_warning "Unknown project type, manual update required"
            ;;
    esac
    
    echo ""
    update_dockerfile
    echo ""
    update_github_actions
    echo ""
    
    # Verify Java installation
    verify_java_installation
    
    echo ""
    echo "======================================================================="
    print_success "Upgrade process completed!"
    echo "======================================================================="
    echo ""
    print_info "Next steps:"
    echo "   1. Review all changes carefully"
    echo "   2. Run: mvn clean install (Maven) or ./gradlew clean build (Gradle)"
    echo "   3. Test your application thoroughly"
    echo "   4. Check java_upgrade_guide.md for detailed migration instructions"
    echo ""
    print_warning "Backup files created with .bak extension"
    echo ""
}

# Run main function
main
