# Terraform Infrastructure for SonarQube
# Generated by AI DevOps Agent

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region"
  default     = "us-east-1"
}

variable "sonarqube_version" {
  description = "SonarQube version to deploy"
  default     = "9.9"
}

resource "aws_instance" "sonarqube_server" {
  ami           = "ami-0c55b159cbfafe1f0"  # Update with appropriate AMI
  instance_type = "t3.medium"
  
  tags = {
    Name        = "SonarQube-${var.sonarqube_version}"
    Environment = "production"
    ManagedBy   = "Terraform"
    Version     = var.sonarqube_version
  }
}

output "sonarqube_instance_id" {
  description = "ID of the SonarQube instance"
  value       = aws_instance.sonarqube_server.id
}

output "sonarqube_public_ip" {
  description = "Public IP of the SonarQube instance"
  value       = aws_instance.sonarqube_server.public_ip
}
