# Terraform Infrastructure for Java
# Generated by AI DevOps Agent

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region"
  default     = "us-east-1"
}

variable "java_version" {
  description = "Java version to deploy"
  default     = "latest"
}

resource "aws_instance" "java_server" {
  ami           = "ami-0c55b159cbfafe1f0"  # Update with appropriate AMI
  instance_type = "t3.medium"
  
  tags = {
    Name        = "Java-${var.java_version}"
    Environment = "production"
    ManagedBy   = "Terraform"
    Version     = var.java_version
  }
}

output "java_instance_id" {
  description = "ID of the Java instance"
  value       = aws_instance.java_server.id
}

output "java_public_ip" {
  description = "Public IP of the Java instance"
  value       = aws_instance.java_server.public_ip
}
